### PR TITLE
WIP: untrack apache/volume

### PR DESCRIPTION
**Pull request by dsavina**
**.gitignore**: do not track folder `apache/volume`

This will allow users to put whatever they want in `apache/volume`, **including their own versioned project**, without having to disconnect root folder from this project.

### CODE REVIEW

**Comment by moufmouf** [comment]
Are you sure you want to put the whole apache/volume in gitignore?
Typically, in one of our project, we put the whole project in apache/volume and versionned the whole project from "."

(we use kickoff-docker-php as a starter kit for our own project so we "export" the project and never update it after) Maybe it would be good to design a "best practice" usage scenario for this tool (are we supposed to copy files? Are we supposed to keep the .git directory and update it regularly?)

**Comment by dsavina** [comment]
I guess the "one solution" is a fiction, there are many possibilities, and each has a reason to be chosen.

With that said, I however think that two factors need to be considered:
- Is docker supposed to be a choice, or a requirement? My guess is that Windows users would probably go for the first option.
- Isn't this project ever going to evolve, and if so, wouldn't it be interesting to be able to keep track? New features might be useful, bug fixes might definitely be necessary (I am not saying there are any, but who knows?).

We just started a new project yesterday, and I went with a classic main branch, `master`, only containing the actual sources, meaning the root path is what would be **apache/volume** folder. I then created an orphan branch, `docker`, originally cloned from **thecodingmachine/kickoff-docker-php** file system, **apache/volume** being a submodule, pointing to a tracked revision of `master`. In brief, branch `docker` is a wrapped dockerized version of the project.

The interest of making **apache/volume** ignored here is that this `docker` branch would not be needed anymore, we could simply keep connection with original docker project.

On the other hand, the drawback is that you would then not be supposed to edit the docker configurations, except for your environment, mapped ports, database connections, etc., so you will have to stick with classic php/mysql/nginx containers. Is that a limitation in your project?

**Comment by Ngob** [comment]
In my opinion, if your branch "docker" is tracked from thecodingmachine/kickoff-docker-php you will have problem if any breaking changes are introduced in a new version ( tags / branch / SEM aren't used on this project). Most of time, you will update your Dockerfile (to add others modules, to update PHP / MYSQL / APACHE...). I think the project owner is responsable of the image's maintenance.
At the moment I think @moufmouf's idea is the best to do without any others update process (I mean, without SEM and file's overriding).

**Comment by gulien** [comment]
I also think @moufmouf's idea is the best. This project should be used as a starter kit.

**Pull request closed without merging**
